version: '3'

services:
  web:
    build: ./web
    ports:
      - "8080:5000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=example
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
